const AllCountries = () => {
  const countries = [
    { id: "1", name: "United Arab Emirates", code: "ae", icon: "flag" },
    { id: "2", name: "Argentina", code: "ar", icon: "flag" },
    { id: "3", name: "Austria", code: "at", icon: "flag" },
    { id: "4", name: "Australia", code: "au", icon: "flag" },
    { id: "5", name: "Belgium", code: "be", icon: "flag" },
    { id: "6", name: "Bulgaria", code: "bg", icon: "flag" },
    { id: "7", name: "Brazil", code: "br", icon: "flag" },
    { id: "8", name: "Canada", code: "ca", icon: "flag" },
    { id: "9", name: "Switzerland", code: "ch", icon: "flag" },
    { id: "10", name: "China", code: "cn", icon: "flag" },
    { id: "11", name: "Colombia", code: "co", icon: "flag" },
    { id: "12", name: "Cuba", code: "cu", icon: "flag" },
    { id: "13", name: "Czech Republic", code: "cz", icon: "flag" },
    { id: "14", name: "Germany", code: "de", icon: "flag" },
    { id: "15", name: "Egypt", code: "eg", icon: "flag" },
    { id: "16", name: "France", code: "fr", icon: "flag" },
    { id: "17", name: "United Kingdom", code: "gb", icon: "flag" },
    { id: "18", name: "Greece", code: "gr", icon: "flag" },
    { id: "19", name: "Hong Kong", code: "hk", icon: "flag" },
    { id: "20", name: "Hungary", code: "hu", icon: "flag" },
    { id: "21", name: "Indonesia", code: "id", icon: "flag" },
    { id: "22", name: "Ireland", code: "ie", icon: "flag" },
    { id: "23", name: "Israel", code: "il", icon: "flag" },
    { id: "24", name: "India", code: "in", icon: "flag" },
    { id: "25", name: "Italy", code: "it", icon: "flag" },
    { id: "26", name: "Japan", code: "jp", icon: "flag" },
    { id: "27", name: "South Korea", code: "kr", icon: "flag" },
    { id: "28", name: "Lithuania", code: "lt", icon: "flag" },
    { id: "29", name: "Latvia", code: "lv", icon: "flag" },
    { id: "30", name: "Morocco", code: "ma", icon: "flag" },
    { id: "31", name: "Mexico", code: "mx", icon: "flag" },
    { id: "32", name: "Malaysia", code: "my", icon: "flag" },
    { id: "33", name: "Nigeria", code: "ng", icon: "flag" },
    { id: "34", name: "Netherlands", code: "nl", icon: "flag" },
    { id: "35", name: "Norway", code: "no", icon: "flag" },
    { id: "36", name: "New Zealand", code: "nz", icon: "flag" },
    { id: "37", name: "Philippines", code: "ph", icon: "flag" },
    { id: "38", name: "Poland", code: "pl", icon: "flag" },
    { id: "39", name: "Portugal", code: "pt", icon: "flag" },
    { id: "40", name: "Romania", code: "ro", icon: "flag" },
    { id: "41", name: "Serbia", code: "rs", icon: "flag" },
    { id: "42", name: "Russia", code: "ru", icon: "flag" },
    { id: "43", name: "Saudi Arabia", code: "sa", icon: "flag" },
    { id: "44", name: "Sweden", code: "se", icon: "flag" },
    { id: "45", name: "Singapore", code: "sg", icon: "flag" },
    { id: "46", name: "Slovakia", code: "sk", icon: "flag" },
    { id: "47", name: "Slovenia", code: "si", icon: "flag" },
    { id: "48", name: "Thailand", code: "th", icon: "flag" },
    { id: "49", name: "Turkey", code: "tr", icon: "flag" },
    { id: "50", name: "Taiwan", code: "tw", icon: "flag" },
    { id: "51", name: "Ukraine", code: "ua", icon: "flag" },
    { id: "52", name: "United States", code: "us", icon: "flag" },
    { id: "53", name: "South Africa", code: "za", icon: "flag" },
    { id: "54", name: "Venezuela", code: "ve", icon: "flag" },
  ];
};
